@URL= http://localhost:8000/

### Get request
GET {{URL}}


### User Router
### Get Request
GET  {{URL}}api/v1/users/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imd5YW5lbjU2QGdtYWlsLmNvbSIsImlhdCI6MTcyNjkxOTA1NCwiZXhwIjoxNzI2OTE5MTE0fQ.rr6Z8X28EaBVkE_T2TGu_Sext55tpTfzHpjKgfSBcQk

### create user
POST {{URL}}api/v1/users/
Content-Type: application/json

{
    "name":"Gyanendra",
    "email":"gyanen56@gmail.com",
    "password":"1234"
}

### Login User
POST {{URL}}api/v1/users/login
Content-Type: application/json

{
    "email":"gyanen56@gmail.com",
    "password":"1234"
}


### Transaction 
POST {{URL}}api/v1/transactions
